name: dedumi

dependencies:
  - base
  - fusion-plugin
  - zlib-bindings
  - cuckoo
  - microlens-th
  - microlens
  - bytestring
  - streamly-bytestring
  - streamly-core
  - ghc-prim

executables:
  dedumi:
    main: dedumi.hs
    ghc-options: [-O2, -fdicts-strict, -fspec-constr-recursive=16, -fmax-worker-args=16, -fplugin=Fusion.Plugin, -Wall, -Wno-name-shadowing]
    other-modules:
      - Data.FastQ
