name: dedumi
license: BSD3
version: 0.1

dependencies:
  - base >= 4.16 && < 5
  - fusion-plugin
  - streaming-commons
  - cuckoo
  - microlens-th
  - microlens
  - bytestring
  - streamly-bytestring
  - streamly-core >= 0.1 && < 0.2
  - ghc-prim
  - optparse-generic

ghc-options: [-O2, -fdicts-strict, -fspec-constr-recursive=16, -fmax-worker-args=16, -fplugin=Fusion.Plugin, -Wall, -Wno-name-shadowing]

executables:
  dedumi:
    main: bin/dedumi.hs
    other-modules:
      - Data.FastQ
      - Dedumi

tests:
  tests:
    main: test.hs
    dependencies:
      - QuickCheck
      - temporary
    other-modules:
      - Data.FastQ

  bench:
    main: bench.hs
    dependencies:
      - QuickCheck
      - criterion
      - temporary
      - text
    other-modules:
      - Data.FastQ
      - Dedumi
