name: dedumi

dependencies:
  - base
  - zlib
  - cuckoo
  - microlens-th
  - microlens
  - bytestring
  - streamly-bytestring
  - streamly
  - streamly-core
  - streamly-archive

executables:
  dedumi:
    main: dedumi.hs
    ghc-options: [-O2, -fspec-constr-recursive=10, -fmax-worker-args=16]
